# Generated by Django 4.0.6 on 2022-07-29 15:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('zip_file', models.FileField(upload_to=dashboard.models.user_directory_path)),
            ],
        ),
    ]
