# Generated by Django 4.0.6 on 2022-07-30 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='downloader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloader', to=settings.AUTH_USER_MODEL),
        ),
    ]
