# Generated by Django 4.0.6 on 2022-08-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_zip_downloader'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='zip_name',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
