# Generated by Django 4.0.6 on 2022-08-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_photo_zip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='origin',
            field=models.CharField(default='no_name yet', max_length=30),
        ),
    ]
