# Generated by Django 4.0.6 on 2022-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_zip_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
