# Generated by Django 4.0.6 on 2022-08-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_zip_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='dashboard.photo'),
        ),
    ]
